#!/usr/bin/env python3
"""
archlora/scrape_stackoverflow.py

Scrapes architecture-related Q&A from Stack Overflow, converts to
ArchRad IR training pairs via GPT-4o.

Stack Overflow posts describe real architecture problems — direct DB access,
missing auth boundaries, sync chains across services. These map directly to
IR-LINT-* violations.

Usage:
  python scrape_stackoverflow.py --dry-run --max-posts 20
  python scrape_stackoverflow.py --max-posts 500
  python scrape_stackoverflow.py --resume

Requirements:
  pip install openai requests

Environment:
  SO_API_KEY     — Stack Overflow API key (stackapps.com/apps/oauth/register)
  OPENAI_API_KEY — OpenAI API key

Output:
  archlora/corpus/stackoverflow-scraped.jsonl
  archlora/corpus/stackoverflow-scraped.DATA_NOTICE.md  (unless --no-data-notice)
  archlora/corpus/stackoverflow-scraped.attribution.txt  (unless --no-attribution)

License / ethics (summary — not legal advice):
  User-generated content on Stack Overflow is generally under CC BY-SA 4.0; see
  https://stackoverflow.com/help/licensing and the Stack Exchange API terms:
  https://api.stackexchange.com/docs/terms-of-use
  This script uses the official API only (no HTML scraping of question pages).
  Training pairs store derived IR + violations, not full post bodies; each row
  carries attribution fields. CC BY-SA may impose ShareAlike and attribution
  obligations on redistributions of adapted material — confirm with counsel
  for your dataset or model distribution plans.
"""

from __future__ import annotations

import argparse
import json
import os
import time
import hashlib
from pathlib import Path
from typing import Optional

ROOT       = Path(__file__).parent.parent
CORPUS_DIR = ROOT / "archlora" / "corpus"
CACHE_DIR  = ROOT / "archlora" / ".so-cache"

SO_API_BASE = "https://api.stackexchange.com/2.3"
SO_HELP_LICENSE = "https://stackoverflow.com/help/licensing"
SO_API_TERMS = "https://api.stackexchange.com/docs/terms-of-use"
CC_BY_SA_4 = "CC BY-SA 4.0"

# Identifying HTTP client (override with env ARCHLORA_HTTP_USER_AGENT)
DEFAULT_USER_AGENT = (
    "archlora-scrape-stackoverflow/1.0 "
    "(+https://github.com/archradhq/arch-deterministic)"
)

DATA_NOTICE_TEMPLATE = """# Data notice — Stack Overflow derived corpus

This file accompanies JSONL produced by `archlora/scrape_stackoverflow.py`.

**Not legal advice.** You are responsible for compliance with the **Stack Exchange
API Terms of Use**, **Stack Overflow / Stack Exchange network terms**, and
**CC BY-SA 4.0** (and other licenses that may apply to specific posts). See:

- {so_license}
- {api_terms}

## What this corpus contains

- Rows are **derived**: ArchRad **IR graphs** and **lint-style violations**
  produced from post text via an LLM. **Full question/answer bodies are not
  stored** in the JSONL; provenance fields (`_source_*`, `_license`) support
  attribution.
- **ShareAlike:** CC BY-SA 4.0 may require that **Adapted Material** you share
  be offered under the same license. Whether a given ML dataset or model
  counts as “adapted material” is **fact-specific** — obtain legal review if
  you redistribute the corpus or derivatives commercially or publicly.

## API use

Data is retrieved via the **official Stack Exchange API** with a registered key,
rate-limit handling, and backoff — not by scraping the website HTML.

---
Generated by `archlora/scrape_stackoverflow.py` (template; file may be rewritten on full runs).
"""

# ─── Search tags — architecture-relevant SO tags ─────────────────────────────

TAG_GROUPS = [
    "software-architecture;event-sourcing",
    "microservices;cqrs",
    "api-design;rate-limiting",
    "software-architecture;domain-driven-design",
    "microservices;circuit-breaker",
    "api-gateway;microservices",
    "software-architecture;security",
    "microservices;kubernetes",
    "system-design;scalability",
    "software-architecture;load-balancing",
    "microservices;saga-pattern",
    "api-design;versioning",
    "software-architecture;hexagonal-architecture",
    "microservices;service-discovery",
    "system-design;caching",
    "software-architecture;microservices",
    "software-architecture;api-design",
    "software-architecture;system-design",
    "microservices;api-gateway",
    "microservices;authentication",
    "microservices;database",
    "software-architecture;authentication",
    "software-architecture;rest",
    "api-design;authentication",
    "system-design;database",
    "microservices;message-queue",
    "software-architecture;caching",
    "microservices;service-mesh",
    "software-architecture;event-driven",
    "api-design;security",
]

ATTRIBUTION_HEADER = f"""# Stack Overflow sources — archlora/scrape_stackoverflow.py
# Network content license: {CC_BY_SA_4} — see {SO_HELP_LICENSE}
# API terms: {SO_API_TERMS}
# Original post text not stored in JSONL — IR derived via GPT-4o (transformative).
# Retain with distributed corpus for CC BY-SA attribution (and ShareAlike as applicable).

"""

# ─── GPT-4o prompt ────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert software architect converting Stack Overflow architecture Q&A into ArchRad IR graphs for AI training.

ArchRad IR format:
{
  "graph": {
    "nodes": [
      {
        "id": "kebab-case-id",
        "type": "gateway|api|bff|service|database|postgres|mongodb|redis|queue|kafka|auth|oauth|jwt|http",
        "name": "Display Name",
        "config": {
          "url": "/health",
          "method": "GET",
          "authRequired": true
        }
      }
    ],
    "edges": [
      {
        "from": "node-id",
        "to": "node-id",
        "metadata": { "protocol": "https|grpc|tcp|async", "async": false }
      }
    ]
  }
}

Node types:
- gateway/api/bff: HTTP entry points, API gateways, BFF layer
- service: backend microservices or domain services
- database/postgres/mongodb/mysql: relational or document stores
- redis/cache: caching layers
- queue/kafka/sqs/rabbitmq: message brokers
- auth/oauth/jwt/keycloak: authentication services
- http: generic HTTP endpoint nodes

Valid violation codes (ONLY these exact strings):
IR-LINT-SYNC-CHAIN-001, IR-LINT-DIRECT-DB-ACCESS-002, IR-LINT-NO-HEALTHCHECK-003,
IR-LINT-HIGH-FANOUT-004, IR-LINT-ISOLATED-NODE-005, IR-LINT-DUPLICATE-EDGE-006,
IR-LINT-HTTP-MISSING-NAME-007, IR-LINT-DATASTORE-NO-INCOMING-008,
IR-LINT-MULTIPLE-HTTP-ENTRIES-009, IR-LINT-MISSING-AUTH-010, IR-LINT-DEAD-NODE-011

RULES:
1. Return ONLY a JSON object with keys "ir" and "violations"
2. "ir" must be a valid IR graph with at least 3 nodes and at least 1 edge
3. "violations" = array of { code, severity: "warning", message, nodeId? }
4. Extract the architecture described in the question/answer — infer components
5. Map architecture problems described in the post to the appropriate violation codes
6. If no meaningful architecture with 3+ components, return {"ir": null, "violations": []}
7. No markdown, no explanation outside the JSON"""


def build_prompt(title: str, question: str, answer: str) -> str:
    # Truncate to fit context
    q = question[:2000] if len(question) > 2000 else question
    a = answer[:1500] if len(answer) > 1500 else answer
    return f"""Convert this Stack Overflow architecture Q&A into an ArchRad IR graph.

Question: {title}

{q}

Best Answer:
{a}

Extract the architecture described, identify components and connections,
map any architecture problems to ArchRad violation codes.

Return: {{"ir": <graph or null>, "violations": [...]}}"""


# ─── Stack Overflow API ───────────────────────────────────────────────────────

def so_get(path: str, params: dict, api_key: str, session) -> Optional[dict]:
    """Make a Stack Overflow API request with caching and backoff."""
    params["key"]  = api_key
    params["site"] = "stackoverflow"

    cache_key  = hashlib.sha256((path + json.dumps(params, sort_keys=True)).encode()).hexdigest()
    cache_file = CACHE_DIR / f"{cache_key}.json"

    if cache_file.exists():
        return json.loads(cache_file.read_text(encoding="utf-8"))

    url = f"{SO_API_BASE}{path}"

    for attempt in range(3):
        try:
            resp = session.get(url, params=params, timeout=15)

            if resp.status_code == 429:
                wait = int(resp.headers.get("Retry-After", 30))
                print(f"  Rate limited — waiting {wait}s...")
                time.sleep(wait)
                continue

            if resp.status_code != 200:
                if attempt < 2:
                    time.sleep(3)
                    continue
                return None

            data = resp.json()

            # Check for backoff signal
            if data.get("backoff"):
                wait = data["backoff"]
                print(f"  SO backoff: waiting {wait}s...")
                time.sleep(wait)

            CACHE_DIR.mkdir(parents=True, exist_ok=True)
            cache_file.write_text(json.dumps(data), encoding="utf-8")
            return data

        except Exception as e:
            if attempt < 2:
                time.sleep(3)
                continue
            return None

    return None


def fetch_questions(tags: str, api_key: str, session, page: int = 1) -> list[dict]:
    """Fetch questions with accepted answers, score > 3."""
    data = so_get(
        "/questions",
        {
            "tagged":        tags,
            "filter":        "withbody",
            "sort":          "votes",
            "order":         "desc",
            "min":           5,        # minimum score
            "pagesize":      20,
            "page":          page,
            "has_accepted_answer": True,
        },
        api_key,
        session,
    )
    if not data:
        return []
    return data.get("items", [])


def fetch_accepted_answer(question_id: int, accepted_answer_id: int,
                          api_key: str, session) -> Optional[str]:
    """Fetch the body of the accepted answer."""
    data = so_get(
        f"/answers/{accepted_answer_id}",
        {"filter": "withbody"},
        api_key,
        session,
    )
    if not data:
        return None
    items = data.get("items", [])
    if not items:
        return None
    # Strip HTML tags simply
    body = items[0].get("body", "")
    body = body.replace("<p>", "\n").replace("</p>", "\n")
    body = body.replace("<br>", "\n").replace("<br/>", "\n")
    # Remove remaining HTML tags
    import re
    body = re.sub(r"<[^>]+>", "", body)
    return body.strip()


# ─── Quality filter ───────────────────────────────────────────────────────────

ARCH_KEYWORDS = [
    "service", "gateway", "api", "database", "cache", "queue", "kafka",
    "auth", "microservice", "component", "architecture", "integration",
    "event", "message", "broker", "proxy", "load balanc", "storage",
    "redis", "postgres", "mongodb", "grpc", "rest", "endpoint",
    "container", "kubernetes", "docker", "deployment",
]


def is_useful_post(title: str, body: str) -> tuple[bool, str]:
    """Filter posts that describe concrete architecture with multiple components."""
    combined = (title + " " + body).lower()

    keyword_hits = [kw for kw in ARCH_KEYWORDS if kw in combined]
    if len(keyword_hits) < 3:
        return False, f"too few architecture keywords ({len(keyword_hits)})"

    if len(body) < 200:
        return False, "body too short"

    return True, "ok"


# ─── GPT-4o conversion ────────────────────────────────────────────────────────

VALID_CODES = frozenset({
    "IR-LINT-SYNC-CHAIN-001", "IR-LINT-DIRECT-DB-ACCESS-002",
    "IR-LINT-NO-HEALTHCHECK-003", "IR-LINT-HIGH-FANOUT-004",
    "IR-LINT-ISOLATED-NODE-005", "IR-LINT-DUPLICATE-EDGE-006",
    "IR-LINT-HTTP-MISSING-NAME-007", "IR-LINT-DATASTORE-NO-INCOMING-008",
    "IR-LINT-MULTIPLE-HTTP-ENTRIES-009", "IR-LINT-MISSING-AUTH-010",
    "IR-LINT-DEAD-NODE-011",
})

BORING_CODES = frozenset({
    "IR-LINT-MULTIPLE-HTTP-ENTRIES-009",
    "IR-LINT-NO-HEALTHCHECK-003",
})


def convert_to_pair(title: str, question: str, answer: str, client) -> Optional[dict]:
    try:
        resp = client.chat.completions.create(
            model           = "gpt-4o",
            messages        = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": build_prompt(title, question, answer)},
            ],
            temperature     = 0.3,
            max_tokens      = 2000,
            response_format = {"type": "json_object"},
        )

        parsed     = json.loads(resp.choices[0].message.content.strip())
        ir         = parsed.get("ir")
        violations = parsed.get("violations", [])

        if not ir or not isinstance(ir, dict):
            return None

        nodes = ir.get("graph", {}).get("nodes", [])
        edges = ir.get("graph", {}).get("edges", [])

        if len(nodes) < 3 or len(edges) < 1:
            return None

        clean_violations = [
            v for v in violations
            if isinstance(v, dict) and v.get("code") in VALID_CODES
        ]

        violation_codes = {v["code"] for v in clean_violations}
        is_boring = bool(violation_codes) and violation_codes.issubset(BORING_CODES)

        return {
            "instruction": "Given this IR graph derived from a real-world architecture question, what architecture violations exist?",
            "input":       ir,
            "output":      {"violations": clean_violations},
            "_boring":     is_boring,
        }

    except Exception:
        return None


# ─── Attribution ──────────────────────────────────────────────────────────────

def append_attribution(fp, *, question_id, title, tags, url, score, answer_id):
    fp.write("---\n")
    fp.write(f"Question-ID: {question_id}\n")
    fp.write(f"Answer-ID: {answer_id}\n")
    fp.write(f"Title: {title}\n")
    fp.write(f"Tags: {', '.join(tags)}\n")
    fp.write(f"URL: {url}\n")
    fp.write(f"Score: {score}\n")
    fp.write(f"License: {CC_BY_SA_4} — {SO_HELP_LICENSE}\n")
    fp.write(f"Stack API terms: {SO_API_TERMS}\n")
    fp.write("\n")


def write_data_notice(path: Path) -> None:
    text = DATA_NOTICE_TEMPLATE.format(
        so_license=SO_HELP_LICENSE,
        api_terms=SO_API_TERMS,
    )
    path.write_text(text, encoding="utf-8")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Stack Overflow → ArchRad training pairs")
    parser.add_argument("--max-posts",     type=int,   default=500)
    parser.add_argument("--out",                       default="archlora/corpus/stackoverflow-scraped.jsonl")
    parser.add_argument("--dry-run",       action="store_true")
    parser.add_argument("--resume",        action="store_true")
    parser.add_argument("--delay",         type=float, default=0.5)
    parser.add_argument("--gpt-delay",     type=float, default=0.5)
    parser.add_argument("--boring-cap",    type=int,   default=50,
                        help="Max pairs with only structural-noise violations (default: 50)")
    parser.add_argument("--no-attribution", action="store_true")
    parser.add_argument("--no-data-notice", action="store_true", help="Do not write *.DATA_NOTICE.md next to JSONL")
    args = parser.parse_args()

    so_key     = os.getenv("SO_API_KEY")
    openai_key = os.getenv("OPENAI_API_KEY")

    if not so_key:
        print("ERROR: SO_API_KEY not set.")
        print("  $env:SO_API_KEY = 'your_key_here'")
        raise SystemExit(1)

    if not openai_key and not args.dry_run:
        print("ERROR: OPENAI_API_KEY not set.")
        print("  $env:OPENAI_API_KEY = 'sk-...'")
        raise SystemExit(1)

    try:
        import requests
    except ImportError:
        print("ERROR: pip install requests")
        raise SystemExit(1)

    client = None
    if not args.dry_run:
        try:
            from openai import OpenAI
            client = OpenAI(api_key=openai_key)
        except ImportError:
            print("ERROR: pip install openai")
            raise SystemExit(1)

    import requests as req_module
    session = req_module.Session()
    ua = os.environ.get("ARCHLORA_HTTP_USER_AGENT", DEFAULT_USER_AGENT)
    session.headers.update({"User-Agent": ua})

    out_path = ROOT / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)

    notice_path = out_path.parent / f"{out_path.stem}.DATA_NOTICE.md"
    if not args.no_data_notice and (not args.resume or not notice_path.exists()):
        write_data_notice(notice_path)

    att_path = None
    if not args.no_attribution and not args.dry_run:
        att_path = out_path.parent / f"{out_path.stem}.attribution.txt"

    # Resume support
    processed_ids = set()
    if args.resume and out_path.exists():
        for line in out_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                try:
                    obj = json.loads(line)
                    if obj.get("_source_id"):
                        processed_ids.add(obj["_source_id"])
                except Exception:
                    pass
        print(f"Resuming: {len(processed_ids)} already done")

    print(f"\nStack Overflow scraper")
    print(f"  Max posts: {args.max_posts}  |  Dry run: {args.dry_run}")
    print(f"  Boring cap: {args.boring_cap}")
    print(f"  Output:    {out_path}")
    if not args.no_data_notice:
        print(f"  Notice:    {notice_path}")
    if att_path:
        print(f"  Attribution: {att_path}")
    print(f"  User-Agent: {ua[:72]}...")
    print()

    total_found   = 0
    total_passed  = 0
    total_pairs   = 0
    total_failed  = 0
    total_boring  = 0
    start         = time.time()

    att_f = None
    if att_path:
        att_mode = "a" if args.resume and att_path.exists() else "w"
        att_f    = open(att_path, att_mode, encoding="utf-8")
        if att_path.stat().st_size == 0:
            att_f.write(ATTRIBUTION_HEADER)

    try:
        with open(out_path, "a" if args.resume else "w", encoding="utf-8") as f:
            for tag_group in TAG_GROUPS:
                if total_found >= args.max_posts:
                    break

                print(f"\nTags: {tag_group}")

                for page in range(1, 6):  # up to 5 pages per tag group
                    if total_found >= args.max_posts:
                        break

                    questions = fetch_questions(tag_group, so_key, session, page=page)
                    if not questions:
                        break

                    for q in questions:
                        if total_found >= args.max_posts:
                            break

                        qid     = q.get("question_id")
                        title   = q.get("title", "")
                        body    = q.get("body", "")
                        tags    = q.get("tags", [])
                        score   = q.get("score", 0)
                        url     = q.get("link", "")
                        ans_id  = q.get("accepted_answer_id")

                        if not qid or not ans_id:
                            continue

                        if qid in processed_ids:
                            continue

                        processed_ids.add(qid)
                        total_found += 1

                        # Strip HTML from question body
                        import re
                        body_clean = re.sub(r"<[^>]+>", "", body.replace("<p>", "\n").replace("</p>", "\n"))

                        # Quality filter
                        ok, reason = is_useful_post(title, body_clean)
                        if not ok:
                            print(f"  [{total_found}] {title[:60]}... — filtered: {reason}")
                            continue

                        total_passed += 1

                        if args.dry_run:
                            print(f"  [{total_found}] ✓ (score:{score}) {title[:70]}...")
                            continue

                        # Fetch accepted answer
                        answer = fetch_accepted_answer(qid, ans_id, so_key, session)
                        if not answer:
                            print(f"  [{total_found}] {title[:60]}... — answer fetch failed")
                            continue

                        time.sleep(args.delay)

                        # Convert via GPT-4o
                        pair = convert_to_pair(title, body_clean, answer, client)

                        if pair is None:
                            total_failed += 1
                            print(f"  [{total_found}] {title[:60]}... — GPT: < 3 nodes / 1 edge")
                        else:
                            is_boring = pair.pop("_boring", False)

                            if is_boring and total_boring >= args.boring_cap:
                                total_failed += 1
                                print(f"  [{total_found}] {title[:60]}... — boring cap reached")
                                time.sleep(args.gpt_delay)
                                continue

                            if is_boring:
                                total_boring += 1

                            row = {
                                "instruction":  pair["instruction"],
                                "input":        pair["input"],
                                "output":       pair["output"],
                                "_source_id":   qid,
                                "_source_url":  url,
                                "_source_title": title,
                                "_source_tags": tags,
                                "_source_score": score,
                                "_license":     CC_BY_SA_4,
                                "_source_license_url": SO_HELP_LICENSE,
                                "_source_stack_api_terms_url": SO_API_TERMS,
                            }
                            f.write(json.dumps(row) + "\n")

                            if att_f:
                                append_attribution(
                                    att_f,
                                    question_id = qid,
                                    title       = title,
                                    tags        = tags,
                                    url         = url,
                                    score       = score,
                                    answer_id   = ans_id,
                                )

                            total_pairs += 1
                            elapsed    = time.time() - start
                            rate       = total_pairs / (elapsed / 60) if elapsed > 0 else 0
                            vcount     = len(pair["output"].get("violations", []))
                            boring_tag = " [boring]" if is_boring else ""
                            print(f"  [{total_found}] ✓ (score:{score}) {title[:55]}... — {vcount} violations  (pairs: {total_pairs}, {rate:.0f}/min){boring_tag}")

                        time.sleep(args.gpt_delay)

                    time.sleep(args.delay)

    finally:
        if att_f:
            att_f.close()

    elapsed = time.time() - start
    print(f"\n{'='*50}")
    print(f"Stack Overflow scraper complete")
    print(f"  Posts fetched:    {total_found}")
    print(f"  Passed filter:    {total_passed}")
    if not args.dry_run:
        print(f"  Pairs generated:  {total_pairs}")
        print(f"  Boring (capped):  {total_boring}/{args.boring_cap}")
        print(f"  GPT skipped:      {total_failed}")
    print(f"  Time:             {elapsed/60:.1f} min")
    print(f"  Output:           {out_path}")
    if not args.no_data_notice:
        print(f"  Data notice:      {notice_path}")
    if att_path and not args.dry_run:
        print(f"  Attribution:      {att_path}")
    if not args.dry_run and total_pairs > 0:
        print(f"\nNext:")
        print(f"  node scripts/combine-corpus.mjs")
        print(f"  python archlora/train.py --split-corpus archlora/corpus/combined.jsonl")


if __name__ == "__main__":
    main()
