#!/usr/bin/env python3
"""
archlora/scrape_apis_guru.py

Fetches real-world OpenAPI specs from apis.guru, converts to ArchRad IR
via `archrad ingest openapi`, validates with `archrad validate --json`,
and emits JSONL training pairs.

No GPT-4o needed — the deterministic engine does the conversion.
IR is real, violations are real.

Data hygiene: uses the official APIs.guru list API, a polite User-Agent,
optional per-row license metadata (list + spec info.license when JSON),
a static DATA_NOTICE next to the JSONL, and an optional .attribution.txt.
This is not legal advice — verify upstream terms for your use case.

Usage:
  python scrape_apis_guru.py --dry-run --max-apis 20
  python scrape_apis_guru.py --max-apis 500
  python scrape_apis_guru.py --resume

Requirements:
  pip install requests
  archrad on PATH (npm i -g @archrad/deterministic), or set ARCHRAD_CLI to archrad.cmd,
  or build this package so dist/cli.js exists and node is on PATH.

Output:
  archlora/corpus/apis-guru-scraped.jsonl
  archlora/corpus/apis-guru-scraped.DATA_NOTICE.md  (unless --no-data-notice)
  archlora/corpus/apis-guru-scraped.attribution.txt  (unless --no-attribution)
"""

from __future__ import annotations

import argparse
import functools
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

ROOT       = Path(__file__).parent.parent
CORPUS_DIR = ROOT / "archlora" / "corpus"
CACHE_DIR  = ROOT / "archlora" / ".apis-guru-cache"

APIS_GURU_LIST_URL = "https://api.apis.guru/v2/list.json"
APIS_GURU_HOME     = "https://apis.guru/"
APIS_GURU_REPO     = "https://github.com/APIs-guru/openapi-directory"

# Identifying HTTP client (override with env ARCHLORA_HTTP_USER_AGENT)
DEFAULT_USER_AGENT = (
    "archlora-scrape-apis-guru/1.0 "
    "(+https://github.com/archradhq/arch-deterministic)"
)

DATA_NOTICE_TEMPLATE = """# Data notice — APIs.guru derived corpus

This file accompanies JSONL produced by `archlora/scrape_apis_guru.py`.

**Not legal advice.** You are responsible for compliance with applicable
terms, licenses, and laws for how you fetch, store, train on, or redistribute
this data.

## Source

- **Catalog:** [APIs.guru OpenAPI Directory]({repo}) — public REST API:
  `{list_url}` (see project README for usage guidance).
- **Training rows:** Each line is **derived** data: ArchRad **IR** and
  deterministic **lint findings** produced locally from an OpenAPI document
  linked from that catalog. **The full upstream OpenAPI file is not stored**
  in the JSONL; provenance fields (`_source_*`, `_list_info`, `_spec_license`)
  support attribution and due diligence.

## Rights

- The **directory project** is published under permissive terms (see the
  repository **LICENSE** — commonly CC0 for contributed definitions; the
  project also describes mixed **upstream** sources).
- **Individual API definitions** may be subject to separate copyright or
  provider terms. The catalog metadata and optional `info.license` fields are
  hints only — confirm with the API publisher if your use requires it.

## Redistribution

If you distribute the JSONL or models trained on it, retain this notice (or
equivalent) and consider retaining `*.attribution.txt` when using
`--no-attribution` disabled.

---
Generated by `archlora/scrape_apis_guru.py` (template; file may be rewritten on full runs).
"""

ATTRIBUTION_HEADER = """# Third-party OpenAPI sources — archlora/scrape_apis_guru.py
# Rows reference APIs.guru catalog entries; IR is derived via archrad, not stored specs.
# Retain with distributed corpus for attribution and license due diligence.

"""

# ─── Filters ──────────────────────────────────────────────────────────────────

# Skip APIs that are too simple to produce meaningful IR
MIN_ENDPOINTS = 3

# Skip very large specs that take too long to process
MAX_SPEC_SIZE_BYTES = 500_000  # 500KB

# Preferred spec format — openapi 3.x preferred over swagger 2.x
PREFERRED_FORMATS = ("openapi", "swagger")

# ─── archrad CLI ──────────────────────────────────────────────────────────────


@functools.lru_cache(maxsize=1)
def _resolve_archrad_argv_cached() -> Optional[tuple[str, ...]]:
    """
    Resolve how to invoke archrad on Windows/macOS/Linux.
    Python's subprocess often fails on bare 'archrad' on Windows even when the shell finds it;
    shutil.which + archrad.cmd fixes that. Override with ARCHRAD_CLI (full command, shlex-split).
    """
    raw = os.environ.get("ARCHRAD_CLI", "").strip()
    if raw:
        parts = shlex.split(raw, posix=os.name != "nt")
        return tuple(parts) if parts else None

    for name in ("archrad", "archrad.cmd", "archrad.exe"):
        p = shutil.which(name)
        if p:
            return (p,)

    cli_js = ROOT / "dist" / "cli.js"
    node = shutil.which("node") or shutil.which("node.exe")
    if cli_js.is_file() and node:
        return (node, str(cli_js.resolve()))

    return None


def resolve_archrad_argv() -> Optional[list[str]]:
    t = _resolve_archrad_argv_cached()
    return list(t) if t else None


def archrad(*args, cwd: Optional[Path] = None, timeout: int = 30) -> tuple[int, str, str]:
    """Run archrad CLI. Returns (returncode, stdout, stderr)."""
    argv = resolve_archrad_argv()
    if not argv:
        print("ERROR: archrad not found.")
        print("  Run: npm i -g @archrad/deterministic")
        print("  Or:  set ARCHRAD_CLI to the full path to archrad.cmd (Windows) or archrad")
        print("  Or:  npm run build in packages/deterministic and ensure node is on PATH")
        sys.exit(1)
    cmd = argv + list(args)
    try:
        result = subprocess.run(
            cmd,
            capture_output = True,
            text           = True,
            timeout        = timeout,
            cwd            = str(cwd) if cwd else None,
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return -1, "", "timeout"
    except FileNotFoundError:
        print("ERROR: archrad subprocess failed (executable missing).")
        print("  Try: set ARCHRAD_CLI to the full path to archrad.cmd")
        sys.exit(1)
    except Exception as e:
        return -1, "", str(e)


def check_archrad() -> bool:
    code, out, _ = archrad("--version")
    if code == 0:
        print(f"archrad version: {out.strip()}")
        return True
    return False


# ─── HTTP + apis.guru API ─────────────────────────────────────────────────────

def http_session():
    import requests

    s = requests.Session()
    ua = os.environ.get("ARCHLORA_HTTP_USER_AGENT", DEFAULT_USER_AGENT)
    s.headers.update({"User-Agent": ua, "Accept": "*/*"})
    return s


def compact_list_info(info: object) -> dict:
    """Small subset of list.json `info` for JSONL provenance."""
    if not isinstance(info, dict):
        return {}
    out: dict = {}
    for k in ("title", "version", "license", "x-apisguru-categories", "x-logo"):
        if k not in info:
            continue
        v = info[k]
        if k == "x-logo" and isinstance(v, dict):
            out[k] = {"url": v.get("url"), "backgroundColor": v.get("backgroundColor")}
        else:
            out[k] = v
    return out


def openapi_info_license(spec_content: str) -> Optional[str]:
    """Best-effort `info.license` from JSON specs; YAML needs PyYAML optional."""
    try:
        data = json.loads(spec_content)
    except json.JSONDecodeError:
        try:
            import yaml  # type: ignore
        except ImportError:
            return None
        try:
            data = yaml.safe_load(spec_content)
        except Exception:
            return None
    if not isinstance(data, dict):
        return None
    info = data.get("info")
    if not isinstance(info, dict):
        return None
    lic = info.get("license")
    if isinstance(lic, str):
        return lic
    if isinstance(lic, dict):
        return lic.get("name") or lic.get("url") or json.dumps(lic, sort_keys=True)
    return None


def fetch_api_list(session) -> dict:
    cache_file = CACHE_DIR / "list.json"

    # Use cached list if less than 24 hours old
    if cache_file.exists():
        age = time.time() - cache_file.stat().st_mtime
        if age < 86400:
            return json.loads(cache_file.read_text(encoding="utf-8"))

    print("Fetching API list from apis.guru...")
    resp = session.get(APIS_GURU_LIST_URL, timeout=30)
    resp.raise_for_status()
    data = resp.json()

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_file.write_text(json.dumps(data), encoding="utf-8")
    print(f"  Found {len(data)} APIs")
    return data


def select_preferred_version(
    api_versions: dict,
) -> Optional[tuple[str, str, str, dict]]:
    """
    Returns (spec_url, version_name, format, version_data) for the best available version.
    Prefers OpenAPI 3.x over Swagger 2.x.
    """
    candidates: list[tuple[str, str, str, dict]] = []

    for version_name, version_data in api_versions.items():
        for fmt in PREFERRED_FORMATS:
            url = (
                version_data.get("swaggerUrl")
                if fmt == "swagger"
                else version_data.get("openApiUrl") or version_data.get("swaggerUrl")
            )
            if url:
                candidates.append((url, version_name, fmt, version_data))
                break

    if not candidates:
        return None

    for url, version, fmt, version_data in candidates:
        if "openapi" in fmt or "3." in version:
            return url, version, fmt, version_data

    u, v, f, vd = candidates[0]
    return u, v, f, vd


def fetch_spec(session, url: str) -> Optional[str]:
    """Fetch OpenAPI spec content with caching."""
    import hashlib

    cache_key = hashlib.md5(url.encode()).hexdigest()
    cache_file = CACHE_DIR / f"spec-{cache_key}.json"

    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8")

    try:
        resp = session.get(url, timeout=20)
        if resp.status_code != 200:
            return None

        content = resp.text

        if len(content.encode()) > MAX_SPEC_SIZE_BYTES:
            return None

        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        cache_file.write_text(content, encoding="utf-8")
        return content

    except Exception:
        return None


def append_apis_guru_attribution(
    fp,
    *,
    api_name: str,
    spec_url: str,
    version_name: str,
    fmt: str,
    list_info_compact: dict,
    spec_license: Optional[str],
) -> None:
    fp.write("---\n")
    fp.write(f"API: {api_name}\n")
    fp.write(f"Spec URL: {spec_url}\n")
    fp.write(f"Version: {version_name}  format: {fmt}\n")
    if list_info_compact:
        fp.write(f"List metadata (compact): {json.dumps(list_info_compact, sort_keys=True)}\n")
    if spec_license:
        fp.write(f"Spec info.license: {spec_license}\n")
    fp.write("\n")


def write_data_notice(path: Path) -> None:
    text = DATA_NOTICE_TEMPLATE.format(
        repo=APIS_GURU_REPO,
        list_url=APIS_GURU_LIST_URL,
    )
    path.write_text(text, encoding="utf-8")


# ─── Conversion pipeline ─────────────────────────────────────────────────────

def spec_to_training_pair(
    spec_content: str,
    api_name: str,
    spec_url: str,
) -> Optional[dict]:
    """
    Run archrad ingest openapi → archrad validate --json.
    Returns a training pair or None if the spec produces no useful IR.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)

        # Write spec to temp file
        spec_path = tmp / "spec.json"
        try:
            # Try to parse as JSON first
            json.loads(spec_content)
            spec_path.write_text(spec_content, encoding="utf-8")
        except json.JSONDecodeError:
            # Might be YAML — write as-is, archrad handles both
            spec_path = tmp / "spec.yaml"
            spec_path.write_text(spec_content, encoding="utf-8")

        ir_path = tmp / "ir.json"

        # Step 1: ingest openapi → IR
        code, out, err = archrad(
            "ingest", "openapi",
            "--spec", str(spec_path),
            "--out",  str(ir_path),
            timeout = 20,
        )

        if code != 0 or not ir_path.exists():
            return None

        # Step 2: validate IR → findings
        code, out, err = archrad(
            "validate",
            "--ir",   str(ir_path),
            "--json",
            "--skip-lint",  # structural only first
            timeout = 20,
        )

        # Re-run with lint enabled (structural errors don't block us here)
        code2, out2, err2 = archrad(
            "validate",
            "--ir",   str(ir_path),
            "--json",
            timeout = 20,
        )

        # Use the lint-enabled output if available
        validate_out = out2 if out2.strip() else out

        # Parse findings
        try:
            findings_raw = json.loads(validate_out)
        except json.JSONDecodeError:
            findings_raw = []

        # Load IR
        try:
            ir = json.loads(ir_path.read_text(encoding="utf-8"))
        except Exception:
            return None

        # Minimum useful IR check
        nodes = ir.get("graph", {}).get("nodes", [])

        if len(nodes) < 3:
            return None

        # archrad validate --json returns a list of findings directly
        if isinstance(findings_raw, list):
            combined = findings_raw
        elif isinstance(findings_raw, dict):
            combined = findings_raw.get("combined", findings_raw.get("findings", []))
        else:
            combined = []

        violations = [
            {
                "code":     f.get("code", ""),
                "severity": f.get("severity", "warning"),
                "message":  f.get("message", ""),
                **({"nodeId": f["nodeId"]} if f.get("nodeId") else {}),
            }
            for f in combined
            if isinstance(f, dict) and f.get("code", "").startswith("IR-LINT-")
        ]

        BORING_CODES = {
            "IR-LINT-MULTIPLE-HTTP-ENTRIES-009",
            "IR-LINT-NO-HEALTHCHECK-003",
        }
        violation_codes = {v["code"] for v in violations}
        is_boring = bool(violation_codes) and violation_codes.issubset(BORING_CODES)

        return {
            "instruction": "Given this IR graph derived from a real-world API specification, what architecture violations exist?",
            "input":       ir,
            "output":      {"violations": violations},
            "_boring":     is_boring,
        }


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="apis.guru → ArchRad training pairs")
    parser.add_argument("--max-apis",  type=int,   default=500)
    parser.add_argument("--out",                   default="archlora/corpus/apis-guru-scraped.jsonl")
    parser.add_argument("--dry-run",   action="store_true", help="List APIs only, no conversion")
    parser.add_argument("--resume",    action="store_true")
    parser.add_argument("--delay",     type=float, default=0.2, help="Delay between API calls (seconds)")
    parser.add_argument("--no-data-notice", action="store_true", help="Do not write *.DATA_NOTICE.md next to JSONL")
    parser.add_argument("--no-attribution", action="store_true", help="Do not append *.attribution.txt per row")
    args = parser.parse_args()

    # Verify archrad is available
    if not check_archrad():
        print("ERROR: archrad --version failed.")
        print("  Run: npm i -g @archrad/deterministic")
        sys.exit(1)

    try:
        import requests
    except ImportError:
        print("ERROR: pip install requests")
        sys.exit(1)

    out_path = ROOT / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)

    notice_path = out_path.parent / f"{out_path.stem}.DATA_NOTICE.md"
    att_path = None
    if not args.no_attribution and not args.dry_run:
        att_path = out_path.parent / f"{out_path.stem}.attribution.txt"

    if not args.no_data_notice and (not args.resume or not notice_path.exists()):
        write_data_notice(notice_path)

    session = http_session()

    # Resume support
    processed_names = set()
    if args.resume and out_path.exists():
        for line in out_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                try:
                    obj = json.loads(line)
                    if obj.get("_source_api"):
                        processed_names.add(obj["_source_api"])
                except Exception:
                    pass
        print(f"Resuming: {len(processed_names)} already done\n")

    print(f"\napis.guru scraper")
    print(f"  Max APIs:  {args.max_apis}  |  Dry run: {args.dry_run}")
    print(f"  Output:    {out_path}")
    if not args.no_data_notice:
        print(f"  Notice:    {notice_path}")
    if att_path:
        print(f"  Attribution: {att_path}")
    print(f"  User-Agent: {session.headers.get('User-Agent', '')[:72]}...")
    print()

    # Fetch API list
    api_list = fetch_api_list(session)

    total_found   = 0
    total_skipped = 0
    total_pairs   = 0
    total_failed  = 0
    total_boring  = 0
    boring_cap    = 100
    start         = time.time()

    att_f = None
    if att_path:
        att_mode = "a" if args.resume and att_path.exists() else "w"
        att_f = open(att_path, att_mode, encoding="utf-8")
        if att_path.stat().st_size == 0:
            att_f.write(ATTRIBUTION_HEADER)

    try:
        with open(out_path, "a" if args.resume else "w", encoding="utf-8") as f:
            for api_name, api_data in api_list.items():
                if total_found >= args.max_apis:
                    break

                if api_name in processed_names:
                    continue

                versions = api_data.get("versions", {})
                if not versions:
                    continue

                spec_info = select_preferred_version(versions)
                if not spec_info:
                    continue

                spec_url, version_name, fmt, version_data = spec_info
                total_found += 1

                if args.dry_run:
                    print(f"  [{total_found}] {api_name} ({version_name}) — {spec_url[:60]}...")
                    if total_found >= args.max_apis:
                        break
                    continue

                # Fetch spec
                spec_content = fetch_spec(session, spec_url)
                if not spec_content:
                    total_skipped += 1
                    print(f"  [{total_found}] {api_name} — fetch failed / too large")
                    continue

                list_info_compact = compact_list_info(version_data.get("info", {}))
                spec_license = openapi_info_license(spec_content)

                # Convert to training pair
                pair = spec_to_training_pair(spec_content, api_name, spec_url)

                if pair is None:
                    total_failed += 1
                    print(f"  [{total_found}] {api_name} — skipped (< 3 nodes / 1 edge)")
                else:                    
                    is_boring = pair.pop("_boring", False)
                    if is_boring and total_boring >= boring_cap:
                        total_failed += 1
                        nodes = len(pair["input"].get("graph", {}).get("nodes", []))
                        print(f"  [{total_found}] {api_name} — skipped (boring cap {boring_cap} reached)")
                        time.sleep(args.delay)
                        continue
                    if is_boring:
                        total_boring += 1

                    row = {
                        "instruction":  pair["instruction"],
                        "input":        pair["input"],
                        "output":       pair["output"],
                        "_source_api":  api_name,
                        "_source_url":  spec_url,
                        "_source_fmt":  fmt,
                        "_source_ver":  version_name,
                        "_source_catalog": "APIs.guru OpenAPI Directory",
                        "_source_catalog_home": APIS_GURU_HOME,
                        "_source_catalog_repo": APIS_GURU_REPO,
                        "_source_list_api": APIS_GURU_LIST_URL,
                    }
                    if list_info_compact:
                        row["_list_info"] = list_info_compact
                    if spec_license:
                        row["_spec_license"] = spec_license

                    f.write(json.dumps(row) + "\n")

                    if att_f:
                        append_apis_guru_attribution(
                            att_f,
                            api_name          = api_name,
                            spec_url          = spec_url,
                            version_name      = version_name,
                            fmt               = fmt,
                            list_info_compact = list_info_compact,
                            spec_license      = spec_license,
                        )

                    total_pairs += 1
                    elapsed  = time.time() - start
                    rate     = total_pairs / (elapsed / 60) if elapsed > 0 else 0
                    vcount   = len(pair["output"].get("violations", []))
                    nodes    = len(pair["input"].get("graph", {}).get("nodes", []))
                    boring_tag = " [boring]" if is_boring else ""
                    print(f"  [{total_found}] ✓ {api_name} — {nodes} nodes, {vcount} violations  (pairs: {total_pairs}, {rate:.0f}/min){boring_tag}")

                time.sleep(args.delay)
    finally:
        if att_f:
            att_f.close()

    elapsed = time.time() - start
    print(f"\n{'='*50}")
    print(f"apis.guru scraper complete")
    print(f"  APIs processed:   {total_found}")
    print(f"  Fetch failed:     {total_skipped}")
    if not args.dry_run:
        print(f"  Pairs generated:  {total_pairs}")
        print(f"  Skipped (small):  {total_failed}")
    print(f"  Time:             {elapsed/60:.1f} min")
    print(f"  Output:           {out_path}")
    print(f"  Boring (capped):  {total_boring}/{boring_cap}")
    if not args.no_data_notice:
        print(f"  Data notice:      {notice_path}")
    if not args.dry_run and total_pairs > 0:
        print(f"\nNext:")
        print(f"  node scripts/combine-corpus.mjs")
        print(f"  python archlora/train.py --split-corpus archlora/corpus/combined.jsonl")


if __name__ == "__main__":
    main()
