import { describe, expect, it } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  buildPolicyPackManifest,
  parsePolicyPackManifest,
  sha256Hex,
  verifyPolicyPackManifest,
  discoverPolicyPackManifest,
  POLICY_PACK_MANIFEST_NAME,
  POLICY_PACK_SIGNATURE_NAME,
} from './policy-pack-sign.js';
import { loadPolicyPacksFromDirectory, loadPolicyPacksFromFiles } from './policy-pack.js';

const VALID_POLICY = `apiVersion: archrad/v1
kind: PolicyPack
metadata:
  name: test-pack
rules:
  - id: TEST-RULE-001
    severity: warning
    message: demo rule
    match:
      node:
        type: service
`;

const ANOTHER_POLICY = `apiVersion: archrad/v1
kind: PolicyPack
metadata:
  name: another
rules:
  - id: TEST-RULE-002
    severity: error
    message: another rule
    match:
      node:
        type: database
`;

describe('sha256Hex', () => {
  it('matches RFC test vectors', () => {
    expect(sha256Hex('')).toBe(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
    );
    expect(sha256Hex('abc')).toBe(
      'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'
    );
  });
});

describe('buildPolicyPackManifest', () => {
  it('sorts entries by filename and includes sha256 prefix', () => {
    const manifest = buildPolicyPackManifest([
      { name: 'b.yaml', content: 'b' },
      { name: 'a.yaml', content: 'a' },
    ]);
    const lines = manifest.trim().split('\n');
    expect(lines).toHaveLength(2);
    expect(lines[0]).toMatch(/^[a-f0-9]{64}  a\.yaml$/);
    expect(lines[1]).toMatch(/^[a-f0-9]{64}  b\.yaml$/);
  });

  it('produces byte-identical output for the same inputs', () => {
    const first = buildPolicyPackManifest([{ name: 'x.yaml', content: VALID_POLICY }]);
    const second = buildPolicyPackManifest([{ name: 'x.yaml', content: VALID_POLICY }]);
    expect(first).toBe(second);
  });

  it('strips leading directory segments from the filename', () => {
    const manifest = buildPolicyPackManifest([
      { name: 'nested/dir/x.yaml', content: 'x' },
    ]);
    expect(manifest).toMatch(/  x\.yaml$/m);
  });
});

describe('parsePolicyPackManifest', () => {
  it('parses sha256sum-style output and ignores comments / blanks', () => {
    const text = `# generated by archrad policies-sha256
${'a'.repeat(64)}  one.yaml

${'b'.repeat(64)}  two.yaml
`;
    const entries = parsePolicyPackManifest(text);
    expect(entries).toEqual([
      { sha256: 'a'.repeat(64), filename: 'one.yaml' },
      { sha256: 'b'.repeat(64), filename: 'two.yaml' },
    ]);
  });

  it('rejects garbage lines with a useful message', () => {
    expect(() => parsePolicyPackManifest('not a hash  foo.yaml\n')).toThrowError(
      /invalid line/
    );
  });

  it('rejects empty manifests', () => {
    expect(() => parsePolicyPackManifest('\n\n# just comments\n')).toThrowError(
      /empty manifest/
    );
  });
});

describe('verifyPolicyPackManifest', () => {
  it('returns ok for matching inputs', () => {
    const sources = [{ name: 'a.yaml', content: 'hello' }];
    const manifest = buildPolicyPackManifest(sources);
    const r = verifyPolicyPackManifest(sources, manifest);
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.verified).toEqual(['a.yaml']);
  });

  it('fails on hash mismatch', () => {
    const sources = [{ name: 'a.yaml', content: 'hello' }];
    const manifest = buildPolicyPackManifest(sources);
    const mutated = sources.map((s) => ({ ...s, content: 'tampered' }));
    const r = verifyPolicyPackManifest(mutated, manifest);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.errors.join('\n')).toMatch(/sha256 mismatch/);
  });

  it('fails when a file is missing from the directory', () => {
    const manifest = buildPolicyPackManifest([
      { name: 'a.yaml', content: 'hello' },
      { name: 'b.yaml', content: 'world' },
    ]);
    const partial = [{ name: 'a.yaml', content: 'hello' }];
    const r = verifyPolicyPackManifest(partial, manifest);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.errors.join('\n')).toMatch(/b\.yaml" listed but missing/);
  });

  it('fails when a file is present but unlisted', () => {
    const manifest = buildPolicyPackManifest([{ name: 'a.yaml', content: 'hello' }]);
    const extra = [
      { name: 'a.yaml', content: 'hello' },
      { name: 'b.yaml', content: 'world' },
    ];
    const r = verifyPolicyPackManifest(extra, manifest);
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.errors.join('\n')).toMatch(/b\.yaml" present.*missing from manifest/);
  });
});

describe('loadPolicyPacksFromFiles with manifest', () => {
  it('reports signedBy=sha256-verified when manifest checks out', () => {
    const sources = [{ name: 'rule.yaml', content: VALID_POLICY }];
    const manifestText = buildPolicyPackManifest(sources);
    const r = loadPolicyPacksFromFiles(sources, { manifest: { manifestText } });
    expect(r.ok).toBe(true);
    if (r.ok) {
      expect(r.ruleCount).toBe(1);
      expect(r.signedBy).toBe('sha256-verified');
    }
  });

  it('fails load when manifest hash does not match', () => {
    const sources = [{ name: 'rule.yaml', content: VALID_POLICY }];
    const manifestText = buildPolicyPackManifest([
      { name: 'rule.yaml', content: 'different content' },
    ]);
    const r = loadPolicyPacksFromFiles(sources, { manifest: { manifestText } });
    expect(r.ok).toBe(false);
  });

  it('reports signedBy=unsigned when no manifest provided', () => {
    const r = loadPolicyPacksFromFiles([{ name: 'rule.yaml', content: VALID_POLICY }]);
    expect(r.ok).toBe(true);
    if (r.ok) expect(r.signedBy).toBe('unsigned');
  });
});

describe('loadPolicyPacksFromDirectory signing integration', () => {
  function makeDir(files: Record<string, string>): string {
    const dir = mkdtempSync(join(tmpdir(), 'archrad-pp-sign-'));
    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(dir, name), content, 'utf8');
    }
    return dir;
  }

  it('loads unsigned when requireSigned is false', async () => {
    const dir = makeDir({ 'a.yaml': VALID_POLICY });
    try {
      const r = await loadPolicyPacksFromDirectory(dir);
      expect(r.ok).toBe(true);
      if (r.ok) expect(r.signedBy).toBe('unsigned');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('fails when --policies-require-signed but manifest missing', async () => {
    const dir = makeDir({ 'a.yaml': VALID_POLICY });
    try {
      const r = await loadPolicyPacksFromDirectory(dir, { requireSigned: true });
      expect(r.ok).toBe(false);
      if (!r.ok) expect(r.errors.join('\n')).toMatch(/manifest.*not found/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('loads signedBy=sha256-verified when manifest is valid', async () => {
    const dir = makeDir({
      'a.yaml': VALID_POLICY,
      'b.yaml': ANOTHER_POLICY,
    });
    try {
      const manifest = buildPolicyPackManifest([
        { name: 'a.yaml', content: VALID_POLICY },
        { name: 'b.yaml', content: ANOTHER_POLICY },
      ]);
      writeFileSync(join(dir, POLICY_PACK_MANIFEST_NAME), manifest, 'utf8');
      const r = await loadPolicyPacksFromDirectory(dir, { requireSigned: true });
      expect(r.ok).toBe(true);
      if (r.ok) {
        expect(r.signedBy).toBe('sha256-verified');
        expect(r.ruleCount).toBe(2);
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('fails when manifest exists but a file was tampered', async () => {
    const dir = makeDir({ 'a.yaml': VALID_POLICY });
    try {
      const originalManifest = buildPolicyPackManifest([
        { name: 'a.yaml', content: VALID_POLICY },
      ]);
      writeFileSync(join(dir, POLICY_PACK_MANIFEST_NAME), originalManifest, 'utf8');
      writeFileSync(join(dir, 'a.yaml'), `${VALID_POLICY}\n# tampered\n`, 'utf8');
      const r = await loadPolicyPacksFromDirectory(dir, { requireSigned: true });
      expect(r.ok).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('cosign failure path: fails with clear error when signature is missing', async () => {
    const dir = makeDir({ 'a.yaml': VALID_POLICY });
    try {
      const manifest = buildPolicyPackManifest([{ name: 'a.yaml', content: VALID_POLICY }]);
      writeFileSync(join(dir, POLICY_PACK_MANIFEST_NAME), manifest, 'utf8');
      const fakeKey = join(dir, 'fake.pub');
      writeFileSync(fakeKey, 'not-a-real-key', 'utf8');
      const r = await loadPolicyPacksFromDirectory(dir, {
        cosignPublicKeyPath: fakeKey,
      });
      expect(r.ok).toBe(false);
      if (!r.ok) {
        expect(r.errors.join('\n')).toMatch(/cosign verification requested/i);
        expect(r.errors.join('\n')).toMatch(/\.sig.*not found/i);
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('discoverPolicyPackManifest', () => {
  it('returns null manifestText when no manifest exists', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'archrad-pp-discover-'));
    try {
      const r = await discoverPolicyPackManifest(dir);
      expect(r.manifestText).toBeNull();
      expect(r.signatureExists).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('returns manifest + signature flags when both exist', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'archrad-pp-discover-'));
    try {
      writeFileSync(join(dir, POLICY_PACK_MANIFEST_NAME), '# empty\n', 'utf8');
      writeFileSync(join(dir, POLICY_PACK_SIGNATURE_NAME), 'sig-blob', 'utf8');
      const r = await discoverPolicyPackManifest(dir);
      expect(r.manifestText).toContain('# empty');
      expect(r.signatureExists).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('ignores directories named like the manifest', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'archrad-pp-discover-'));
    try {
      mkdirSync(join(dir, POLICY_PACK_SIGNATURE_NAME));
      const r = await discoverPolicyPackManifest(dir);
      expect(r.signatureExists).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
